---
- name: Restart SSH
  ansible.builtin.systemd:
    name: ssh
    state: restarted

- name: Restart NTP
  ansible.builtin.systemd:
    name: systemd-timesyncd
    state: restarted
  when: ansible_facts['os_family'] == 'Debian'  