---
- name: "Clone dotfiles repo"
  ansible.builtin.git:
    repo: 'https://github.com/der-faebu/dotfiles'
    dest: "/home/{{ username }}/.dotfiles"
    recursive: yes
  remote_user: "{{ username }}"

- name: "Set permissions for dotfile directory" 
  ansible.builtin.file:
    path: "/home/{{ username }}/.dotfiles"
    owner: "{{ username }}"
    group: "{{ username }}"
    recurse: yes
    mode: "0755"

- name: "Create symlinks for dotfiles"
  ansible.builtin.shell:
    cmd: "stow -t /home/{{ username }} -d /home/{{ username }}/.dotfiles -S {{ item }}"
  loop: "{{ dotfiles.home_dir_packages }}"
  remote_user: "{{ username }}"