---
- name: "Clone dotfiles repo"
  ansible.builtin.git:
    repo: 'https://github.com/der-faebu/dotfiles'
    dest: "/home/{{ username }}/.dotfiles"
    recursive: true
    force: true
    version: main  # noqa: latest
  become: true
  become_user: "{{ username }}"
  become_method: su

# this is somewhat hacky for bashrc
- name: "Create symlinks for dotfiles"
  become: true
  become_user: "{{ username }}"
  become_method: su
  ansible.builtin.command:
    cmd: "stow -t /home/{{ username }} -d /home/{{ username }}/.dotfiles -S {{ item }} --adopt"
  loop: "{{ dotfiles.home_dir_packages }}"
  register: stow_out
  changed_when: stow_out != 0

- name: "Git restore"
  become: true
  become_user: "{{ username }}"
  become_method: su
  ansible.builtin.command: # noqa: command-instead-of-module
    cmd: "git restore ."
  args:
    chdir: "/home/{{ username }}/.dotfiles"
  changed_when: false
